### ISSUE TITLE
generate blur data

### ISSUE THREAD

**Issue by ms-ufad** [rimchang/RSBlur#2]
Hello, how to use the blur data generation model proposed in the paper? I want to generate some blur data. thank you。

**Comment by rimchang** [comment]
Due to the significant computational time, we save synthetic blurred images in advance using averaging after frame interpolation. Then, we apply saturation synthesis, noise synthesis, and camera ISP during training. 

For generating new blurred images, you have to generate your own synthetic blurred images using averaging or synthetic blur kernels. After, you can apply our synthesis method for more realistic blurred images during training.

We link related codes below.

Best regard.

1, Saturation synthesis : https://github.com/rimchang/RSBlur/blob/31ecd24cc5a5f7e79f99a3c6495507d5b8f67fca/SRN-Deblur-RSBlur/models/model.py#L107
2, Noise synthesis with ISP : https://github.com/rimchang/RSBlur/blob/31ecd24cc5a5f7e79f99a3c6495507d5b8f67fca/SRN-Deblur-RSBlur/models/model.py#L283
3, Adopting CRF : https://github.com/rimchang/RSBlur/blob/31ecd24cc5a5f7e79f99a3c6495507d5b8f67fca/SRN-Deblur-RSBlur/models/model.py#L302
